// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getDatabasePath: () => __TAURI_INVOKE<string>("get_database_path"),
	getDatabaseSize: () => typedError<number, string>(__TAURI_INVOKE("get_database_size")),
	getConfig: () => __TAURI_INVOKE<Config>("get_config"),
	saveConfig: (config: Config) => typedError<null, string>(__TAURI_INVOKE("save_config", { config })),
	startIndexing: (blacklist: string[]) => typedError<null, string>(__TAURI_INVOKE("start_indexing", { blacklist })),
};

/* Types */
export type Config = {
	settings?: SettingsConfig,
	indexing?: IndexingConfig,
};

export type IndexingConfig = {
	excluded_paths?: string[],
};

export type SettingsConfig = {
	theme?: Theme,
	disable_keyboard_shortcut_hints?: boolean | null,
	enable_debug_menu?: boolean | null,
};

export type Theme = "Dark" | "Light" | "System";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

